### ISSUE TITLE
can't connect to host - Mac OS X SSL Certificates

### ISSUE THREAD

**Issue by nicknew3d** [MMquant/Websocket-orderbook-replication#1]
I've upgraded to python 3.4, installed asyncio etc, but when I run the code I get errors, any idea what might be going wrong? I'm afraid my understanding of websockets is pretty shaky but I'm trying to set up an arbitrage bot and this seems to be the way to go. great blog by the way!
this is what I get:

$ python3 streaming_tests_asyncio.py 
enter get_book, pair: ETCBTC
enter get_book, pair: BTCUSD
Task exception was never retrieved
future: <Task finished coro=<print_books() done, defined at streaming_tests_asyncio.py:96> exception=KeyError('bids',)>
Traceback (most recent call last):
  File "streaming_tests_asyncio.py", line 102, in print_books
    bids = [[v[1], v[0], k] for k, v in orderbooks[pair]['bids'].items()]
KeyError: 'bids'
Task exception was never retrieved
future: <Task finished coro=<get_book() done, defined at streaming_tests_asyncio.py:112> exception=ClientConnectorError(65, 'Cannot connect to host api.bitfinex.com:443 ssl:True [Can not connect to api.bitfinex.com:443 [No route to host]]')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 710, in _create_direct_connection
    local_addr=self._local_addr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 777, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 764, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 456, in _sock_connect
    sock.connect(address)
OSError: [Errno 65] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 737, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Can not connect to api.bitfinex.com:443 [No route to host]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "streaming_tests_asyncio.py", line 117, in get_book
    async with session.ws_connect('wss://api.bitfinex.com/ws/2') as ws:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 390, in _ws_connect
    proxy_auth=proxy_auth)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/helpers.py", line 97, in __iter__
    ret = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Cannot connect to host api.bitfinex.com:443 ssl:True [Can not connect to api.bitfinex.com:443 [No route to host]]
Task exception was never retrieved
future: <Task finished coro=<get_book() done, defined at streaming_tests_asyncio.py:112> exception=ClientConnectorError(65, 'Cannot connect to host api.bitfinex.com:443 ssl:True [Can not connect to api.bitfinex.com:443 [No route to host]]')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 710, in _create_direct_connection
    local_addr=self._local_addr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 777, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 764, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 456, in _sock_connect
    sock.connect(address)
OSError: [Errno 65] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 737, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Can not connect to api.bitfinex.com:443 [No route to host]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "streaming_tests_asyncio.py", line 117, in get_book
    async with session.ws_connect('wss://api.bitfinex.com/ws/2') as ws:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 390, in _ws_connect
    proxy_auth=proxy_auth)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/helpers.py", line 97, in __iter__
    ret = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Cannot connect to host api.bitfinex.com:443 ssl:True [Can not connect to api.bitfinex.com:443 [No route to host]]

**Comment by MMquant** [comment]
Hi,
Could you open an issue on github? If somebody else will have the same problem then the public solution may help her. I will have a look in a few days into it.

Maple

**Comment by nicknew3d** [comment]
Hey, sorry for this, my ignorance in how github works.... you sent me a message through github which I received by email:
***
Hi,
Could you open an issue on github? If somebody else will have the same problem then the public solution may help her. I will have a look in a few days into it.

Maple
***
....this is an issue on github! and I can't work out how to reply to your message apart from writing a comment here :oP ...anyway thanks for your swift reply, I hope you get to look into the issue soon, I'm very interested to see this working.
Thanks, Nick.

**Comment by MMquant** [comment]
I just tried the code on my machine with python3.6 and it works. The replicator code is ok. It looks you can't fetch data from Bitfinex API. What version of aiohttp and websockets do you have?

**Comment by nicknew3d** [comment]
Thank you for looking, I'm actually on python 3.6, the libraries you mention are all up to date on 3.6 too, I've tried disabling my antivirus software in case that was interrupting the connection somehow but still can't connect. 
if I go here: http://websocket.org/echo.html 
and connect with: wss://api.bitfinex.com/ws/2
I get:
CONNECTED
RECEIVED: {"event":"info","version":1.1
so doesn't appear to be a connection problem
is there a very simple aiohttp or async script I can run to test it within that workflow?

**Comment by MMquant** [comment]
This is barebone core script for websocket connection. Tested with _aiohttp (2.0.7)_. I actually noted that I don't use _websockets_ library at all. The _aiohttp_ library includes methods for websocket connection.

```
import aiohttp
import asyncio

SUB_MESG = {
    'event': 'subscribe',
    'channel': 'book',
    'freq': 'F1',
    'len': '25',
    'prec': 'P0',
    'pair': 'BTCUSD'
}

async def get_book(pair, session):
    """ Subscribes for orderbook updates and fetches updates. """
    print('enter get_book, pair: {}'.format(pair))
    async with session.ws_connect('wss://api.bitfinex.com/ws/2') as ws:
        ws.send_json(SUB_MESG)
        while 1:
            res = await ws.receive()
            print(res.data)  # debug

async def main():
    """ Driver coroutine. """
    async with aiohttp.ClientSession() as session:
        await get_book('BTCUSD', session)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

What os do you use? If OS X I remember that I had troubles with PYTHON <---> SSL/TLS <---> HOST connections. I needed to install root certificates for python SSL module. The out-of-the-box installation script `Install Certificates.command` can be found in Applications/ in Python installation directory.

Try to connect without SSL - that is use just `ws://api.bitfinex.com/ws/2`.

**Comment by nicknew3d** [comment]
I have it working, I am using osx.... 
Install Certificates.command did the job, no idea why that's required!?
also I did try ws instead of wss, I was expecting it to use another port but it still complained about 443, anyway that's by the by, I will have a tinker with this and see where it takes me, websocket gives a whole new range of possibilities over REST
thanks you for your help!
Nick.
